version: "3.9"
services:
  master:
    image: redis:6.2.8
    container_name: master
    restart: always
    ports:
      - 16381:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --replica-announce-ip ${HOST_IP} --replica-announce-port 16381
    networks:
      - redis-sentinel
  slave1:
    image: redis:6.2.8
    container_name: slave1
    restart: always
    depends_on:
      - master
    ports:
      - 16382:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof master 6379 --masterauth redis --replica-announce-ip ${HOST_IP} --replica-announce-port 16382
    networks:
      - redis-sentinel
  slave2:
    image: redis:6.2.8
    container_name: slave2
    restart: always
    depends_on:
      - master
    ports:
      - 16383:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof master 6379 --masterauth redis --replica-announce-ip ${HOST_IP} --replica-announce-port 16383
    networks:
      - redis-sentinel
  sentinel1:
    image: redis:6.2.8
    container_name: sentinel1
    restart: always
    depends_on:
      - master
      - slave1
      - slave2
    ports:
      - 16386:26379
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - redis-sentinel
  sentinel2:
    image: redis:6.2.8
    container_name: sentinel2
    restart: always
    depends_on:
      - master
      - slave1
      - slave2
    ports:
      - 16387:26379
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - redis-sentinel
  sentinel3:
    image: redis:6.2.8
    container_name: sentinel3
    restart: always
    depends_on:
      - master
      - slave1
      - slave2
    ports:
      - 16388:26379
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    networks:
      - redis-sentinel

networks:
  redis-sentinel: